# Generated by Django 3.0.6 on 2021-02-27 12:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='followees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='author',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='followieng', to=settings.AUTH_USER_MODEL),
        ),
    ]
